// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sadin.Cms.Persistence;

#nullable disable

namespace Sadin.Cms.Persistence.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20230503100847_AuditableProperties_Add")]
    partial class AuditableProperties_Add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sadin.Cms.Domain.Aggregates.ContactUs.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages", (string)null);
                });

            modelBuilder.Entity("Sadin.Cms.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccuredDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Sadin.Cms.Persistence.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessageConsumers", (string)null);
                });

            modelBuilder.Entity("Sadin.Cms.Domain.Aggregates.ContactUs.ContactMessage", b =>
                {
                    b.OwnsOne("Sadin.Cms.Domain.Aggregates.ContactUs.ValueObjects.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("ContactMessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Content");

                            b1.HasKey("ContactMessageId");

                            b1.ToTable("ContactMessages");

                            b1.WithOwner()
                                .HasForeignKey("ContactMessageId");
                        });

                    b.OwnsOne("Sadin.Cms.Domain.Aggregates.ContactUs.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ContactMessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("ContactMessageId");

                            b1.ToTable("ContactMessages");

                            b1.WithOwner()
                                .HasForeignKey("ContactMessageId");
                        });

                    b.OwnsOne("Sadin.Cms.Domain.Aggregates.ContactUs.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("ContactMessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FullName");

                            b1.HasKey("ContactMessageId");

                            b1.ToTable("ContactMessages");

                            b1.WithOwner()
                                .HasForeignKey("ContactMessageId");
                        });

                    b.OwnsOne("Sadin.Cms.Domain.Aggregates.ContactUs.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("ContactMessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("ContactMessageId");

                            b1.ToTable("ContactMessages");

                            b1.WithOwner()
                                .HasForeignKey("ContactMessageId");
                        });

                    b.OwnsOne("Sadin.Cms.Domain.Aggregates.ContactUs.ValueObjects.Subject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("ContactMessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Subject");

                            b1.HasKey("ContactMessageId");

                            b1.ToTable("ContactMessages");

                            b1.WithOwner()
                                .HasForeignKey("ContactMessageId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("Subject")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
